let in4 =[{
   Email:"gobrbrbrbr@gmail.com",
   Phone:"0123456789",
   Password:"qwertyuiop",
   Username:"None",
},
{
    Email:"brbrbrbr@gmail,com",
    Phone:"0123467890",
    Password:"asdfghjkl",
    Username:"StillNone",
},
{
    Email:"khongcoemail@gmail.com",
    Phone:"0198765432",
    Password:"jiddjdjdj",
    Username:"StillNone1",
},
]
localStorage.setItem("Infor",JSON.stringify(in4))
